language: python
python: '3.7'
install:
- pip install numpy
- pip install scipy
- pip install numba
- pip install pytest
- pip install pytest-cov
- pip install codecov
- pip install -e .
matrix:
  include:
  # Main job, uses numba.
  - script: py.test --cov=kickscore
  # Secondary job, disables numba & computes code coverage.
  - script: py.test --cov=kickscore
    env: NUMBA_DISABLE_JIT=1
    after_success: codecov
deploy:
  provider: pypi
  user: lum
  password:
    secure: mPyVkTY9RB3vN7mqrZYB00yq9aqfxk7FqUBlpek3GkDij1DY28SdKVxYmsfAqP7OPhwy3lEzGlf3MvfyKPWKzzblx8op/ed7hlMmfAkPYYSWpRG9AuEnqRDpSaJdMtFxzWNnRye/aRk4lfrYNuXEFv0KfUGQtQWiGOZf82t+torDTnvqccHjs5HM2rqwYU7sSYZcOMPKbuW0Ml9p6eNUSX5z/3oVg1WSqSizOXRjQ0C9Sj0LQc7/S9K/YCnGA9AyL9W4Mh+tv6JDBOSTzRCfL+bZGO9Jpxyi+Bw8pqQZ/uEbyDwqXeEuXKy6wjKkISOKy44jQKwULXeWj15I4Qs3J6aJW9CRihN9MeMdKUvKeQ3Ac8+xH7T7ewC8z8Zk/NT7B9xKMTIp8NE+gL32xpp46HiecFBD3OpqPiEFMi1XCY19kHLzNrFC8thvpLKCdqFYtdQDlk4HA+peaKBzqL0XT0k5JxbIQfLXJEAwi6wjBJn6caczmrxVYBw9A3ML9BGrvaYCg7vHC/jVHD1dD1pVLB/QjPPMQByYoUMqxPH3qWV7UxTeJ0L6V0PR/uCOaZxAbdgH3RPFnYfwZSW/K5PtQNVvF7mCq43QntC3xx1pBjCQMK9o+xWbJOQgY40GtTHch5yBiIcDr4yMKJpxYa9O5vyiXIanH3Imn91+TOnCjKg=
  on:
    tags: true
    branch: master
  skip_existing: true
  distributions: "sdist bdist_wheel"
