language: python
python: '3.5'
install:
  - pip install numpy
  - pip install scipy
  - pip install numba
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install -e .
matrix:
  include:
  # Main job, uses numba.
  - script: py.test --cov=kickscore
  # Secondary job, disables numba & computes code coverage.
  - script: py.test --cov=kickscore
    env: NUMBA_DISABLE_JIT=1
    after_success: codecov
